apiVersion: v1
kind: Service
metadata:
  name: jenkins-app1
  namespace: jenkins-app1
  labels:
    app: jenkins-app1
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: jenkins-app1