apiVersion: v1
kind: Service
metadata:
  name: ldap
  namespace: jenkins-app1
  labels:
    app: ldap
spec:
  ports:
    - name: ldap
      port: 389
    - name: ldap-s
      port: 636
  selector:
    app: ldap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap
  namespace: jenkins-app1
  labels:
    app: ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ldap
  template:
    metadata:
      labels:
        app: ldap
        version: latest
    spec:
      containers:
        - name: ldap
          image: rroemhild/test-openldap:latest
          ports:
            - containerPort: 389
            - containerPort: 636
          resources:
            limits:
              cpu: 1
              memory: 1024Mi
