apiVersion: v1
kind: Pod
metadata:
  name: shell-utils
  namespace: jenkins-app1
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: shell-utils
    image: gcr.io/test-tf-arch-test-dev-prj-001/shell-utils:latest
    resources:
      limits:
        cpu: 10m
        memory: 256Mi
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
